### ISSUE TITLE
[CRITICAL] Crash to desktop under Arch Linux

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPL3BankEditor#193]
Init audioOut...
Using RtAudio driver: jack
RtApiJack::getDeviceInfo: error determining Jack input/output channels!

RtApiJack::getDeviceInfo: error determining Jack input/output channels!
Desired latency 0.02
Buffer size 960
terminate called after throwing an instance of 'RtAudioError'
  what():  RtApiJack::probeDeviceOpen: requested number of channels (2) + offset (0) not found for specified device (0:Family 17h/19h HD Audio Controller Digital Microphone).
Przerwane (zrzut pamięci)
[anon@shitbox ~]$ 

build didnt fail...

**Comment by freq-mod** [comment]
It works under Wine

**Comment by Wohlstand** [comment]
You should disable the JACK at RtAudio module 👀
(I'll try to take a look at code sooner, but now I am out of home)

**Comment by freq-mod** [comment]
Trying to build using vendored rtaudio and rtmidi doesnt work, it moans about RtAudio.h cant be found

**Comment by Wohlstand** [comment]
Did you clonned submodules?
```
git submodule init
git submodule update
```

**Comment by freq-mod** [comment]
yes

**Comment by Wohlstand** [comment]
I fixed the CMake build that you noted (QMake build works just fine): https://github.com/Wohlstand/OPL3BankEditor/commit/193bf190c71723707d13fd0d2aa930b41741b578

**Comment by Wohlstand** [comment]
I also added an option to disable Jack support at vendored RtAudio.

**Comment by freq-mod** [comment]
OK so it builds, but still crashes... will try to disable jack

**Comment by Wohlstand** [comment]
According to the log, it's just a failure of RtAudio that never tries other APIs and goes "Use JACK or die!"

**Comment by freq-mod** [comment]
disableing jack fixes the crash. thanks!

**Comment by Wohlstand** [comment]
I'll apply the same fix to the OPN2 Bank Editor too.
